theme: minima
title: about yeab
author: yeabsera dessalegn
email: yeabudesse3@gmail.com
description:this is just very lil thing about me

# social links
facebook_username: Yeabsera Dessalegn
github_username:  yeab-yeab
telegram_username: emyeye
instagram_username: yeab___

show_excerpts: true # set to false to remove excerpts on the homepage
